# Generated by Django 4.2.1 on 2023-05-13 20:02

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.TextField(blank=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
