# Generated by Django 4.2.1 on 2023-05-13 20:05

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_profile_image_alter_profile_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quotes',
            field=models.TextField(blank=True, max_length=1000, verbose_name=django.contrib.auth.models.User),
        ),
    ]
