# Generated by Django 4.2.1 on 2023-05-17 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_profile_date_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='facebook',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter',
            field=models.CharField(default='#', max_length=1000),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
