# Generated by Django 4.2.1 on 2023-05-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/images/profile_9mPx2EJ.png', upload_to='static/images'),
        ),
    ]
