# Generated by Django 4.2.1 on 2023-05-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
    ]
