# Generated by Django 4.2.1 on 2023-05-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_title_alter_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='White', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(default='Cotton,Jeans', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='Regular', max_length=100),
        ),
    ]
