# Generated by Django 4.2.1 on 2023-06-03 05:42

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping_info',
            field=models.TextField(default='This is product shipping info.'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty_info',
            field=models.TextField(default='This is product warranty info.'),
        ),
        migrations.AddField(
            model_name='seller',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='this is seller description'),
        ),
    ]
