# Generated by Django 4.2.1 on 2023-06-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_shipping_info_product_warranty_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
