# Generated by Django 4.2.1 on 2023-06-04 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_image_1_product_image_2_product_image_3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
