# Generated by Django 4.2.1 on 2023-06-04 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rating_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='phone',
        ),
    ]
