# Generated by Django 4.2.1 on 2023-06-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_product_category_remove_product_offer_and_more'),
        ('shop', '0017_alter_product_offer_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.categorie'),
        ),
    ]
