# Generated by Django 4.2.1 on 2023-06-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_offer_expired_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='coupon',
            field=models.CharField(default='COUPON', max_length=50),
        ),
    ]
