# Generated by Django 4.2.1 on 2023-06-07 13:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0020_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(default='', max_length=100)),
                ('signature', models.CharField(default='', max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('product_id', models.IntegerField()),
                ('price', models.BigIntegerField()),
                ('quantity', models.IntegerField()),
                ('total', models.BigIntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 6, 7, 13, 28, 31, 227448, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
